# NB: this is only used for local development
# see Dockerfile for deployed version

django:
  build: .
  command: ./run.sh start
  volumes:
    # - .:/app
    - /tmp/pip_download_cache:/root/.cache/pip
  ports:
    - "8004:8004"
  environment:
    ENV: local
    DEBUG: "True"
    DJANGO_SECRET_KEY: CHANGE_ME
